import json
from collections.abc import Awaitable, Callable, Sequence
from typing import Any, TypedDict

from decomposer.core import SubagentType, create_decomposer_agent
from fastapi import Body, Request, Response
from langchain.agents.middleware import AgentMiddleware, ModelRequest, ModelResponse
from langchain_core.callbacks import AsyncCallbackManagerForLLMRun, CallbackManagerForLLMRun
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from langchain_core.tools import BaseTool
from langchain_core.utils.function_calling import convert_to_openai_tool
from pydantic import ConfigDict, ImportString

from nemo_gym.base_resources_server import (
    AggregateMetrics,
    AggregateMetricsRequest,
    BaseRunRequest,
    BaseVerifyRequest,
    BaseVerifyResponse,
)
from nemo_gym.base_responses_api_agent import BaseResponsesAPIAgentConfig, SimpleResponsesAPIAgent
from nemo_gym.config_types import ModelServerRef, ResourcesServerRef
from nemo_gym.global_config import get_first_server_config_dict
from nemo_gym.openai_utils import (
    NeMoGymEasyInputMessage,
    NeMoGymFunctionCallOutput,
    NeMoGymResponse,
    NeMoGymResponseCreateParamsNonStreaming,
    NeMoGymResponseFunctionToolCall,
    NeMoGymResponseInput,
    NeMoGymResponseInputItem,
    NeMoGymResponseOutputItem,
    NeMoGymResponseUsage,
)
from nemo_gym.server_utils import get_response_json, raise_for_status


MISSING_FINAL_ASSISTANT_FAILURE_CLASS = "decomposer_missing_final_assistant_message"
MISSING_FINAL_ASSISTANT_MESSAGE = "Decomposer response did not contain a final assistant message."
UNCOLLECTED_SUBAGENTS_FAILURE_CLASS = "decomposer_uncollected_subagents"
UNCOLLECTED_SUBAGENTS_MESSAGE = "Decomposer finalized before collecting all subagent reports"
NG_FAILURE_CLASS_KEY = "_ng_failure_class"
NG_FAILURE_DETAIL_KEY = "_ng_failure_detail"
TERMINAL_SUBAGENT_STATUSES = frozenset({"success", "error", "timeout", "interrupted"})


class DecomposerRolloutValidationError(RuntimeError):
    """A retryable post-hoc validation failure for one Decomposer rollout."""

    def __init__(self, failure_class: str, detail: str):
        super().__init__(detail)
        self.failure_class = failure_class


class MissingFinalAssistantMessageError(DecomposerRolloutValidationError):
    """The Decomposer stopped without producing an answer for the verifier."""

    def __init__(self):
        super().__init__(
            MISSING_FINAL_ASSISTANT_FAILURE_CLASS,
            MISSING_FINAL_ASSISTANT_MESSAGE,
        )


class UncollectedSubagentsError(DecomposerRolloutValidationError):
    """The Decomposer answered before every spawned subagent report was collected."""

    def __init__(self, details: str):
        super().__init__(
            UNCOLLECTED_SUBAGENTS_FAILURE_CLASS,
            f"{UNCOLLECTED_SUBAGENTS_MESSAGE}: {details}.",
        )


class ChatNeMoGym(BaseChatModel):
    """Gym model-server wrapper that can be used as `decomposer_model` in
    `create_decomposer_agent`.

    How it works:
    - `create_decomposer_agent` passes this model to LangChain's `create_agent`.
    - `create_agent` owns the agent loop. On every model step, it calls
      `bind_tools()` with `spawn_subagent` and `wait` tools and then calls
      `ainvoke()`.
    - `bind_tools()` converts LangChain/OpenAI tool schemas to Gym Responses API
      function-tool schemas and stores them as bound kwargs.
    - `BaseChatModel.ainvoke()` eventually calls `_agenerate()` with the current
      LangChain messages plus bound kwargs such as `tools` and `tool_choice`.
    - `_agenerate()` starts from the original Gym request body, replaces only
      `input` with the current LangChain `messages`, applies bound `tools` /
      `tool_choice` kwargs,
      calls the configured Gym model server `/v1/responses`, and converts the
      Gym `NeMoGymResponse` back to a LangChain `AIMessage`.
    - Runtime AI messages generated by this wrapper carry the raw Gym response
      in `ChatResult.llm_output["nemo_gym_response"]`; LangChain copies that
      into `AIMessage.response_metadata`. `ainvoke()` asserts this contract.
    - On later model calls, output AI messages are replayed from the exact
      stored Gym response output items. This preserves Gym-native trajectory and
      training fields instead of reconstructing them from LangChain messages.
    - Input AI messages (e.g. few-shot examples) might not have
      `nemo_gym_response`; they are converted from normal LangChain `content`
      and `tool_calls`.
    - Model-server cookies are stored in
      `ChatResult.llm_output["nemo_gym_cookies"]` and replayed to the next model
      request, matching Gym official examples.
    - Malformed function-call arguments become `AIMessage.invalid_tool_calls`.
      `create_agent` will not execute them; any repair/retry policy should be
      implemented outside this model wrapper.

    Note that we implement only `ainvoke` and `_agenerate`, because in the
    `DecomposerAgent` below only `ainvoke` is used.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)

    server_client: Any
    model_server_name: str

    @property
    def _llm_type(self) -> str:
        return "nemo_gym"

    async def ainvoke(
        self,
        input: Any,
        config: Any | None = None,
        *,
        stop: list[str] | None = None,
        **kwargs: Any,
    ) -> AIMessage:
        """Run the normal `BaseChatModel` path and assert LangChain metadata behavior."""
        message = await super().ainvoke(input, config=config, stop=stop, **kwargs)
        missing_metadata = {"nemo_gym_response", "nemo_gym_cookies"} - set(message.response_metadata)
        if missing_metadata:
            raise RuntimeError(
                "Expected LangChain to copy `ChatResult.llm_output` into "
                "`AIMessage.response_metadata`, but missing keys: "
                f"{sorted(missing_metadata)}"
            )
        return message

    def _generate(
        self,
        messages: list[BaseMessage],
        stop: list[str] | None = None,
        run_manager: CallbackManagerForLLMRun | None = None,
        **kwargs: Any,
    ) -> ChatResult:
        raise NotImplementedError("`ChatNeMoGym` supports async generation only.")

    async def _agenerate(
        self,
        messages: list[BaseMessage],
        stop: list[str] | None = None,
        run_manager: AsyncCallbackManagerForLLMRun | None = None,
        **kwargs: Any,
    ) -> ChatResult:
        """Call the configured Gym model server once.

        The request body starts from the original Gym `/v1/responses` body passed
        through runtime `context` by `NeMoGymDecomposerAgentMiddleware`. We replace only
        `input` for the current model step and then apply kwargs bound by
        `create_agent`, mainly `tools` and `tool_choice`.
        """
        if stop:
            raise NotImplementedError("`ChatNeMoGym` does not support `stop` sequences yet.")

        body = kwargs.pop("nemo_gym_body", None)
        if body is None:
            raise RuntimeError("`ChatNeMoGym` expected `NeMoGymDecomposerAgentMiddleware` to pass `nemo_gym_body`.")
        body = NeMoGymResponseCreateParamsNonStreaming.model_validate(body).model_dump(exclude_unset=True)
        body["input"] = _messages_to_items(messages)

        for key in ("max_output_tokens", "temperature", "top_p", "top_logprobs", "parallel_tool_calls"):
            if kwargs.get(key) is not None:
                body[key] = kwargs[key]
        if kwargs.get("max_tokens") is not None and kwargs.get("max_output_tokens") is None:
            body["max_output_tokens"] = kwargs["max_tokens"]

        tools = kwargs.get("tools")
        if not tools:
            raise RuntimeError("`ChatNeMoGym` expected `create_agent` to bind non-empty Decomposer `tools`.")
        body["tools"] = [_to_responses_tool(tool) for tool in tools]

        tool_choice = kwargs.get("tool_choice")
        body["tool_choice"] = _to_responses_tool_choice(tool_choice) if tool_choice is not None else "auto"

        body = NeMoGymResponseCreateParamsNonStreaming.model_validate(body)

        model_response = await self.server_client.post(
            server_name=self.model_server_name,
            url_path="/v1/responses",
            json=body,
            cookies=_latest_cookies(messages),
        )
        await raise_for_status(model_response)
        response_json = await get_response_json(model_response)
        response = NeMoGymResponse.model_validate(response_json)

        message = _response_to_ai_message(response)
        return ChatResult(
            generations=[ChatGeneration(message=message)],
            llm_output={
                # LangChain copies `llm_output` into `AIMessage.response_metadata` for
                # the single-generation case. `DecomposerAgent.responses()` can then
                # recover Gym-native outputs without custom graph middleware.
                "nemo_gym_response": response_json,
                # Keep Gym/aiohttp cookies as-is, matching official Gym examples.
                # The next model call scans prior AI messages and passes them back.
                "nemo_gym_cookies": model_response.cookies,
            },
        )

    def bind_tools(
        self,
        tools: Sequence[dict[str, Any] | type | Callable[..., Any] | BaseTool],
        *,
        tool_choice: str | None = None,
        **kwargs: Any,
    ):
        """Bind Decomposer tools in the format expected by Gym Responses API.

        `create_agent` calls this before every model invocation when `tools` are
        available. `self.bind(...)` stores these kwargs until `BaseChatModel.ainvoke()`
        eventually forwards them to `_agenerate()`.
        """
        bound_kwargs = {"tools": [_to_responses_tool(tool) for tool in tools]}
        if tool_choice is not None:
            bound_kwargs["tool_choice"] = _to_responses_tool_choice(tool_choice)
        bound_kwargs.update(kwargs)
        return self.bind(**bound_kwargs)


class NeMoGymContext(TypedDict):
    body: dict[str, Any]
    resource_server_url: str
    resource_server_cookies: dict[str, str]


class NeMoGymDecomposerAgentMiddleware(AgentMiddleware):
    def wrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], ModelResponse],
    ) -> ModelResponse:
        return handler(_request_with_body(request))

    async def awrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], Awaitable[ModelResponse]],
    ) -> ModelResponse:
        return await handler(_request_with_body(request))


def _default_response_for_verifier_factory(
    nemo_gym_response: NeMoGymResponse,
    final_state: dict[str, Any],
    responses_create_params: NeMoGymResponseCreateParamsNonStreaming,
) -> NeMoGymResponse:
    return nemo_gym_response


def _subagent_tool_calls_and_final_message(
    nemo_gym_response: NeMoGymResponse,
    final_state: dict[str, Any],
    responses_create_params: NeMoGymResponseCreateParamsNonStreaming,
) -> NeMoGymResponse:
    final_assistant_message = None
    for item in reversed(nemo_gym_response.output):
        if _item_get(item, "type") == "message" and _item_get(item, "role") == "assistant":
            final_assistant_message = item
            break
    if final_assistant_message is None:
        raise MissingFinalAssistantMessageError()

    response_data = nemo_gym_response.model_dump(mode="json")
    request_data = responses_create_params.model_dump(mode="json")
    response_data["output"] = [
        *(
            tool_call.model_dump(mode="json", exclude_none=True)
            for tool_call in _collect_subagent_tool_calls(final_state)
        ),
        final_assistant_message.model_dump(mode="json", exclude_none=True),
    ]
    for field_name in ("tools", "tool_choice", "parallel_tool_calls"):
        response_data[field_name] = request_data[field_name]
    return NeMoGymResponse.model_validate(response_data)


class DecomposerAgentConfig(BaseResponsesAPIAgentConfig):
    resources_server: ResourcesServerRef
    model_server: ModelServerRef
    subagent_types: Sequence[SubagentType]
    few_shot_message_factories: Sequence[
        ImportString[Callable[[], Sequence[dict[str, Any]]]]
    ] = ()
    join_gym_system_and_user_prompts: bool = False
    response_for_verifier_factory: ImportString[
        Callable[
            [
                NeMoGymResponse,
                dict[str, Any],
                NeMoGymResponseCreateParamsNonStreaming,
            ],
            NeMoGymResponse,
        ]
    ] = _default_response_for_verifier_factory


class DecomposerAgentRunRequest(BaseRunRequest):
    model_config = ConfigDict(extra="allow")


class DecomposerAgentVerifyRequest(BaseVerifyRequest):
    model_config = ConfigDict(extra="allow")


class DecomposerAgentVerifyResponse(BaseVerifyResponse):
    model_config = ConfigDict(extra="allow")


class DecomposerAgentResponse(NeMoGymResponse):
    """Internal response transport between `/v1/responses` and `/run`."""

    final_state: dict[str, Any]


class DecomposerAgent(SimpleResponsesAPIAgent):
    """Gym agent server for the first Decomposer version.

    Assumes LangGraph SDK subagent assistants are already running. Gym function
    tools and the seeded resource-server session are passed to every subagent run.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)
    config: DecomposerAgentConfig

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.graph = create_decomposer_agent(
            decomposer_model=ChatNeMoGym(
                server_client=self.server_client,
                model_server_name=self.config.model_server.name,
            ),
            subagent_types=self.config.subagent_types,
            middleware=[NeMoGymDecomposerAgentMiddleware()],
            context_schema=NeMoGymContext,
        )

    def _resources_server_base_url(self) -> str:
        config = get_first_server_config_dict(
            self.server_client.global_config_dict,
            self.config.resources_server.name,
        )
        return self.server_client._build_server_base_url(config)

    async def responses(
        self,
        request: Request,
        response: Response,
        body: NeMoGymResponseCreateParamsNonStreaming = Body(),
    ) -> DecomposerAgentResponse:
        body = body.model_copy(deep=True)

        input_messages = _input_to_messages(
            body.input,
            join_gym_system_and_user_prompts=self.config.join_gym_system_and_user_prompts,
        )
        few_shot_messages = [
            message
            for factory in self.config.few_shot_message_factories
            for message in factory()
        ]
        initial_messages = [*few_shot_messages, *input_messages]
        initial_state = {"messages": initial_messages}
        final_state = await self.graph.ainvoke(
            initial_state,
            context={
                "body": body.model_dump(mode="json", exclude_unset=True),
                "resource_server_url": self._resources_server_base_url(),
                "resource_server_cookies": dict(request.cookies),
            },
        )
        all_messages = final_state["messages"]
        output_messages = all_messages[len(initial_messages) :]
        output_items = _messages_to_items(output_messages)
        usage = _messages_to_usage(output_messages)

        model_response = None
        for message in reversed(output_messages):
            if isinstance(message, AIMessage) and "nemo_gym_response" in message.response_metadata:
                model_response = message.response_metadata["nemo_gym_response"]
                break
        if model_response is None:
            raise RuntimeError("Decomposer graph did not produce a `ChatNeMoGym` model response.")

        for k, v in request.cookies.items():
            response.set_cookie(k, v)
        model_server_cookies = _latest_cookies(output_messages)
        if model_server_cookies is not None:
            for k, v in model_server_cookies.items():
                response.set_cookie(k, v)

        return DecomposerAgentResponse.model_validate(
            model_response
            | {
                "output": output_items,
                "usage": usage,
                "final_state": final_state,
            }
        )

    async def run(
        self,
        request: Request,
        body: DecomposerAgentRunRequest = Body(),
    ) -> DecomposerAgentVerifyResponse:
        cookies = request.cookies

        seed_session_response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/seed_session",
            json=body.model_dump(),
            cookies=cookies,
        )
        await raise_for_status(seed_session_response)
        cookies = seed_session_response.cookies

        response = await self.server_client.post(
            server_name=self.config.name,
            url_path="/v1/responses",
            json=body.responses_create_params,
            cookies=cookies,
        )
        await raise_for_status(response)
        cookies = response.cookies

        decomposer_agent_response = DecomposerAgentResponse.model_validate(await get_response_json(response))
        nemo_gym_response = NeMoGymResponse.model_validate(
            decomposer_agent_response.model_dump(mode="json", exclude={"final_state"})
        )
        try:
            _validate_decomposer_rollout(
                nemo_gym_response,
                decomposer_agent_response.final_state,
            )
        except DecomposerRolloutValidationError as e:
            # An incomplete terminal state is a failed rollout, not an agent-server
            # failure. Keep the canonical response for diagnosis and route the
            # sample to the retryable sidecar without calling the task verifier.
            return DecomposerAgentVerifyResponse.model_validate(
                body.model_dump(mode="json")
                | {
                    "response": nemo_gym_response.model_dump(mode="json"),
                    "reward": 0.0,
                    NG_FAILURE_CLASS_KEY: e.failure_class,
                    NG_FAILURE_DETAIL_KEY: str(e),
                }
            )

        response_for_verifier = self.config.response_for_verifier_factory(
            nemo_gym_response,
            decomposer_agent_response.final_state,
            body.responses_create_params,
        )
        verify_request = DecomposerAgentVerifyRequest.model_validate(
            body.model_dump() | {"response": response_for_verifier}
        )

        verify_response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/verify",
            json=verify_request.model_dump(),
            cookies=cookies,
        )
        await raise_for_status(verify_response)
        verify_response_data = await get_response_json(verify_response)
        verify_response_data["response"] = nemo_gym_response.model_dump(mode="json")
        verify_response_data["final_state"] = decomposer_agent_response.final_state
        return DecomposerAgentVerifyResponse.model_validate(verify_response_data)

    async def aggregate_metrics(self, body: AggregateMetricsRequest = Body()) -> AggregateMetrics:
        response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/aggregate_metrics",
            json=body.model_dump(),
        )
        await raise_for_status(response)
        return AggregateMetrics.model_validate(await get_response_json(response))


def _input_to_messages(
    input: str | NeMoGymResponseInput,
    *,
    join_gym_system_and_user_prompts: bool = False,
) -> list[BaseMessage]:
    """Convert Gym Responses API `input` into LangChain `messages`."""
    if isinstance(input, str):
        return [HumanMessage(content=input)]

    messages = []
    for item in input:
        item_type = _item_get(item, "type")
        if item_type == "message":
            role = _item_get(item, "role")
            content = _input_content_to_text(_item_get(item, "content", ""))

            if role == "user":
                message = HumanMessage(content=content)
            elif role in {"system", "developer"}:
                message = SystemMessage(content=content)
            elif role == "assistant":
                message = AIMessage(content=content)
            else:
                raise NotImplementedError(f"Unsupported Gym message `role`: {role!r}")

        elif item_type == "function_call":
            arguments = _item_get(item, "arguments", "")
            call_id = _item_get(item, "call_id")
            name = _item_get(item, "name")
            try:
                args = json.loads(arguments)
            except json.JSONDecodeError as e:
                message = AIMessage(
                    content="",
                    invalid_tool_calls=[
                        {
                            "type": "invalid_tool_call",
                            "id": call_id,
                            "name": name,
                            "args": arguments,
                            "error": f"Invalid JSON arguments: {e}",
                        }
                    ],
                )
            else:
                if not isinstance(args, dict):
                    message = AIMessage(
                        content="",
                        invalid_tool_calls=[
                            {
                                "type": "invalid_tool_call",
                                "id": call_id,
                                "name": name,
                                "args": arguments,
                                "error": "Tool-call arguments must be a JSON object.",
                            }
                        ],
                    )
                else:
                    message = AIMessage(
                        content="",
                        tool_calls=[{"name": name, "args": args, "id": call_id}],
                    )
        elif item_type == "function_call_output":
            message = ToolMessage(
                content=_input_content_to_text(_item_get(item, "output", "")),
                tool_call_id=_item_get(item, "call_id"),
            )
        else:
            if item_type in _MULTIMODAL_CONTENT_TYPES:
                raise NotImplementedError(
                    "`DecomposerAgent` supports text-only input; "
                    f"multimodal input item type {item_type!r} is not supported."
                )
            raise NotImplementedError(f"Unsupported Gym input item `type`: {item_type!r}")

        messages.append(message)

    if (
        join_gym_system_and_user_prompts
        and len(messages) == 2
        and isinstance(messages[0], SystemMessage)
        and isinstance(messages[1], HumanMessage)
    ):
        return [HumanMessage(content=f"{messages[0].text}\n\n{messages[1].text}")]

    return messages


def _request_with_body(request: ModelRequest) -> ModelRequest:
    body = _item_get(request.runtime.context, "body")
    if body is None:
        raise RuntimeError("`NeMoGymDecomposerAgentMiddleware` expected runtime `context.body`.")

    model_settings = dict(request.model_settings)
    model_settings["nemo_gym_body"] = NeMoGymResponseCreateParamsNonStreaming.model_validate(body)
    return request.override(model_settings=model_settings)


def _collect_subagent_tool_calls(
    final_state: dict[str, Any],
) -> list[NeMoGymResponseFunctionToolCall]:
    subagent_runs = final_state.get("subagent_runs") or {}
    function_calls: list[NeMoGymResponseFunctionToolCall] = []
    reported_subagent_runs = sorted(
        (
            subagent_run
            for subagent_run in subagent_runs.values()
            if subagent_run.get("report_sequence_number") is not None
        ),
        key=lambda subagent_run: subagent_run["report_sequence_number"],
    )
    for subagent_run in reported_subagent_runs:
        subagent_run_id = subagent_run["subagent_run_id"]
        for tool_call in subagent_run.get("tool_calls") or []:
            function_calls.append(
                NeMoGymResponseFunctionToolCall(
                    name=tool_call["name"],
                    arguments=json.dumps(tool_call["args"], ensure_ascii=False),
                    call_id=f"{subagent_run_id}_{tool_call['id']}",
                    status="completed",
                )
            )

    return function_calls


def _validate_decomposer_rollout(
    nemo_gym_response: NeMoGymResponse,
    final_state: dict[str, Any],
) -> None:
    """Reject terminal graph states that are unsafe to send to the verifier."""
    final_messages = final_state.get("messages") or []
    if not final_messages:
        raise MissingFinalAssistantMessageError()

    terminal_message = final_messages[-1]
    terminal_type = _item_get(terminal_message, "type")
    terminal_content = _message_content_to_text(_item_get(terminal_message, "content", ""))
    terminal_tool_calls = _item_get(terminal_message, "tool_calls", []) or []
    if terminal_type != "ai" or terminal_tool_calls or not terminal_content.strip():
        raise MissingFinalAssistantMessageError()

    if not any(
        _item_get(item, "type") == "message" and _item_get(item, "role") == "assistant"
        for item in nemo_gym_response.output
    ):
        raise MissingFinalAssistantMessageError()

    invalid_runs: list[str] = []
    for subagent_run_id, subagent_run in (final_state.get("subagent_runs") or {}).items():
        status = _item_get(subagent_run, "status")
        report = _item_get(subagent_run, "report")
        report_sequence_number = _item_get(
            subagent_run,
            "report_sequence_number",
        )
        reasons = []
        if status not in TERMINAL_SUBAGENT_STATUSES:
            reasons.append(f"non-terminal status {status!r}")
        if report is None:
            reasons.append("missing report")
        else:
            if _item_get(report, "subagent_run_id") != subagent_run_id:
                reasons.append("report run ID does not match")
            if _item_get(report, "status") != status:
                reasons.append("report status does not match")
        if (
            isinstance(report_sequence_number, bool)
            or not isinstance(report_sequence_number, int)
            or report_sequence_number < 0
        ):
            reasons.append("missing or invalid report sequence number")
        if reasons:
            invalid_runs.append(f"`{subagent_run_id}` ({'; '.join(reasons)})")

    if invalid_runs:
        raise UncollectedSubagentsError(", ".join(invalid_runs))


def _messages_to_items(messages: list[BaseMessage]) -> list[NeMoGymResponseInputItem | NeMoGymResponseOutputItem]:
    """Convert LangChain `messages` into Gym Responses API input/output items."""
    items = []
    for message in messages:
        if isinstance(message, HumanMessage):
            items.append(
                NeMoGymEasyInputMessage(role="user", content=_message_content_to_text(message.content)).model_dump()
            )
        elif isinstance(message, SystemMessage):
            items.append(
                NeMoGymEasyInputMessage(role="system", content=_message_content_to_text(message.content)).model_dump()
            )
        elif isinstance(message, ToolMessage):
            items.append(
                NeMoGymFunctionCallOutput(
                    call_id=message.tool_call_id,
                    output=_message_content_to_text(message.content),
                    status="completed",
                ).model_dump(exclude_none=True)
            )
        elif isinstance(message, AIMessage):
            if "nemo_gym_response" in message.response_metadata:
                # Preferred path for runtime messages generated by `ChatNeMoGym`:
                # replay the exact Gym model-server output, including training fields.
                output_items = message.response_metadata["nemo_gym_response"]["output"]
            else:
                # Fallback for hand-authored LangChain assistant messages, especially
                # future few-shot examples. These are prompt items only; they should not
                # be treated as generated rollout output by `DecomposerAgent.responses()`.
                output_items = []
                if message.content:
                    output_items.append(
                        NeMoGymEasyInputMessage(
                            role="assistant",
                            content=_message_content_to_text(message.content),
                        ).model_dump()
                    )
                for tool_call in message.tool_calls:
                    output_items.append(
                        NeMoGymResponseFunctionToolCall(
                            name=tool_call["name"],
                            arguments=json.dumps(tool_call["args"]),
                            call_id=tool_call["id"],
                            status="completed",
                        ).model_dump(exclude_none=True)
                    )
            items.extend(output_items)
        else:
            raise NotImplementedError(f"Unsupported LangChain message `type`: {type(message).__name__}")

    return items


def _messages_to_usage(messages: list[BaseMessage]) -> NeMoGymResponseUsage | None:
    usage = None
    for message in messages:
        if not isinstance(message, AIMessage):
            continue

        response = message.response_metadata.get("nemo_gym_response")
        if isinstance(response, NeMoGymResponse):
            response_usage = response.usage
        elif isinstance(response, dict) and response.get("usage") is not None:
            response_usage = NeMoGymResponseUsage.model_validate(response["usage"])
        else:
            response_usage = None

        if response_usage is None:
            continue

        if usage is None:
            usage = response_usage.model_copy(deep=True)
        else:
            usage.input_tokens += response_usage.input_tokens
            usage.input_tokens_details.cached_tokens += response_usage.input_tokens_details.cached_tokens
            usage.output_tokens += response_usage.output_tokens
            usage.output_tokens_details.reasoning_tokens += response_usage.output_tokens_details.reasoning_tokens
            usage.total_tokens += response_usage.total_tokens

    return usage


def _response_to_ai_message(response: NeMoGymResponse) -> AIMessage:
    """Project one Gym response into the `AIMessage` shape `create_agent` expects."""
    texts: list[str] = []
    tool_calls: list[dict[str, Any]] = []
    invalid_tool_calls: list[dict[str, Any]] = []

    for item in response.output:
        if item.type == "message":
            for content in item.content:
                if content.type == "output_text":
                    texts.append(content.text)
                elif content.type == "refusal":
                    texts.append(content.refusal)
        elif item.type == "function_call":
            try:
                args = json.loads(item.arguments)
            except json.JSONDecodeError as e:
                # Invalid tool calls are represented with LangChain's standard
                # field. `create_agent` will not execute them; repair/retry policy
                # belongs in an optional middleware, not this model wrapper.
                invalid_tool_calls.append(
                    {
                        "type": "invalid_tool_call",
                        "id": item.call_id,
                        "name": item.name,
                        "args": item.arguments,
                        "error": f"Invalid JSON arguments: {e}",
                    }
                )
                continue

            if not isinstance(args, dict):
                # LangChain executable tool calls require dict args.
                invalid_tool_calls.append(
                    {
                        "type": "invalid_tool_call",
                        "id": item.call_id,
                        "name": item.name,
                        "args": item.arguments,
                        "error": "Tool-call arguments must be a JSON object.",
                    }
                )
                continue

            tool_calls.append({"name": item.name, "args": args, "id": item.call_id})

    usage_metadata = None
    if response.usage is not None:
        usage_metadata = {
            "input_tokens": response.usage.input_tokens,
            "output_tokens": response.usage.output_tokens,
            "total_tokens": response.usage.total_tokens,
        }

    return AIMessage(
        content="\n".join(text for text in texts if text),
        tool_calls=tool_calls,
        invalid_tool_calls=invalid_tool_calls,
        usage_metadata=usage_metadata,
    )


def _latest_cookies(messages: list[BaseMessage]) -> Any | None:
    """Return the most recent model-server cookies stored on an AI message."""
    for message in reversed(messages):
        if not isinstance(message, AIMessage):
            continue
        if "nemo_gym_cookies" in message.response_metadata:
            return message.response_metadata["nemo_gym_cookies"]
    return None


def _to_responses_tool(tool: dict[str, Any] | type | Callable[..., Any] | BaseTool) -> dict[str, Any]:
    openai_tool = tool if isinstance(tool, dict) else convert_to_openai_tool(tool)

    if openai_tool.get("type") == "function" and "function" in openai_tool:
        responses_tool = {"type": "function", **openai_tool["function"]}
    elif openai_tool.get("type") == "function":
        responses_tool = dict(openai_tool)
    else:
        return openai_tool

    responses_tool.setdefault("strict", False)
    return responses_tool


def _to_responses_tool_choice(tool_choice: Any) -> Any:
    if isinstance(tool_choice, str):
        return tool_choice
    if isinstance(tool_choice, dict) and tool_choice.get("type") == "function" and "function" in tool_choice:
        return {"type": "function", "name": tool_choice["function"]["name"]}
    return tool_choice


def _message_content_to_text(content: Any) -> str:
    return _content_to_text(content, source="LangChain")


def _input_content_to_text(content: Any) -> str:
    return _content_to_text(content, source="Gym")


_TEXT_CONTENT_TYPES = frozenset({"text", "input_text", "output_text"})
_MULTIMODAL_CONTENT_TYPES = frozenset(
    {
        "audio",
        "computer_call_output",
        "file",
        "image",
        "image_generation_call",
        "image_url",
        "input_audio",
        "input_file",
        "input_image",
        "video",
    }
)


def _content_to_text(content: Any, *, source: str) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        raise NotImplementedError(
            f"`DecomposerAgent` supports only string or text-part {source} message content; "
            f"received {type(content).__name__}."
        )

    texts = []
    for part in content:
        if isinstance(part, str):
            texts.append(part)
            continue

        part_type = _item_get(part, "type")
        if part_type in _MULTIMODAL_CONTENT_TYPES:
            raise NotImplementedError(
                f"`DecomposerAgent` supports text-only input; multimodal {source} "
                f"content part type {part_type!r} is not supported."
            )
        if part_type in _TEXT_CONTENT_TYPES:
            text = _item_get(part, "text")
        elif part_type == "refusal":
            text = _item_get(part, "refusal")
        else:
            raise NotImplementedError(f"Unsupported {source} message content part `type`: {part_type!r}")

        if not isinstance(text, str):
            raise ValueError(f"{source} message content part {part_type!r} must contain string text.")
        texts.append(text)

    return "\n".join(texts)


def _item_get(item: Any, key: str, default: Any = None) -> Any:
    if isinstance(item, dict):
        return item.get(key, default)
    return getattr(item, key, default)


if __name__ == "__main__":
    DecomposerAgent.run_webserver()
