import json
from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass
from typing import Any

from decomposer.core import SubagentType, create_decomposer_agent
from fastapi import Body, Request, Response
from langchain.agents.middleware import AgentMiddleware, ModelRequest, ModelResponse
from langchain_core.callbacks import AsyncCallbackManagerForLLMRun, CallbackManagerForLLMRun
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from langchain_core.tools import BaseTool
from langchain_core.utils.function_calling import convert_to_openai_tool
from pydantic import ConfigDict

from nemo_gym.base_resources_server import (
    AggregateMetrics,
    AggregateMetricsRequest,
    BaseRunRequest,
    BaseVerifyRequest,
    BaseVerifyResponse,
)
from nemo_gym.base_responses_api_agent import BaseResponsesAPIAgentConfig, SimpleResponsesAPIAgent
from nemo_gym.config_types import ModelServerRef, ResourcesServerRef
from nemo_gym.openai_utils import (
    NeMoGymEasyInputMessage,
    NeMoGymFunctionCallOutput,
    NeMoGymResponse,
    NeMoGymResponseCreateParamsNonStreaming,
    NeMoGymResponseFunctionToolCall,
    NeMoGymResponseInput,
    NeMoGymResponseInputItem,
    NeMoGymResponseOutputItem,
    NeMoGymResponseUsage,
)
from nemo_gym.server_utils import get_response_json, raise_for_status


class ChatNeMoGym(BaseChatModel):
    """Gym model-server wrapper that can be used as `decomposer_model` in
    `create_decomposer_agent`.

    How it works:
    - `create_decomposer_agent` passes this model to LangChain's `create_agent`.
    - `create_agent` owns the agent loop. On every model step, it calls
      `bind_tools()` with `spawn_subagent` and `wait` tools and then calls
      `ainvoke()`.
    - `bind_tools()` converts LangChain/OpenAI tool schemas to Gym Responses API
      function-tool schemas and stores them as bound kwargs.
    - `BaseChatModel.ainvoke()` eventually calls `_agenerate()` with the current
      LangChain messages plus bound kwargs such as `tools` and `tool_choice`.
    - `_agenerate()` starts from the original Gym request body, replaces only
      `input` with the current LangChain `messages`, applies bound `tools` /
      `tool_choice` kwargs,
      calls the configured Gym model server `/v1/responses`, and converts the
      Gym `NeMoGymResponse` back to a LangChain `AIMessage`.
    - Runtime AI messages generated by this wrapper carry the raw Gym response
      in `ChatResult.llm_output["nemo_gym_response"]`; LangChain copies that
      into `AIMessage.response_metadata`. `ainvoke()` asserts this contract.
    - On later model calls, output AI messages are replayed from the exact
      stored Gym response output items. This preserves Gym-native trajectory and
      training fields instead of reconstructing them from LangChain messages.
    - Input AI messages (e.g. few-shot examples) might not have
      `nemo_gym_response`; they are converted from normal LangChain `content`
      and `tool_calls`.
    - Model-server cookies are stored in
      `ChatResult.llm_output["nemo_gym_cookies"]` and replayed to the next model
      request, matching Gym official examples.
    - Malformed function-call arguments become `AIMessage.invalid_tool_calls`.
      `create_agent` will not execute them; any repair/retry policy should be
      implemented outside this model wrapper.

    Note that we implement only `ainvoke` and `_agenerate`, because in the
    `DecomposerAgent` below only `ainvoke` is used.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)

    server_client: Any
    model_server_name: str

    @property
    def _llm_type(self) -> str:
        return "nemo_gym"

    async def ainvoke(
        self,
        input: Any,
        config: Any | None = None,
        *,
        stop: list[str] | None = None,
        **kwargs: Any,
    ) -> AIMessage:
        """Run the normal `BaseChatModel` path and assert LangChain metadata behavior."""
        message = await super().ainvoke(input, config=config, stop=stop, **kwargs)
        missing_metadata = {"nemo_gym_response", "nemo_gym_cookies"} - set(message.response_metadata)
        if missing_metadata:
            raise RuntimeError(
                "Expected LangChain to copy `ChatResult.llm_output` into "
                "`AIMessage.response_metadata`, but missing keys: "
                f"{sorted(missing_metadata)}"
            )
        return message

    def _generate(
        self,
        messages: list[BaseMessage],
        stop: list[str] | None = None,
        run_manager: CallbackManagerForLLMRun | None = None,
        **kwargs: Any,
    ) -> ChatResult:
        raise NotImplementedError("`ChatNeMoGym` supports async generation only.")

    async def _agenerate(
        self,
        messages: list[BaseMessage],
        stop: list[str] | None = None,
        run_manager: AsyncCallbackManagerForLLMRun | None = None,
        **kwargs: Any,
    ) -> ChatResult:
        """Call the configured Gym model server once.

        The request body starts from the original Gym `/v1/responses` body passed
        through runtime `context` by `NeMoGymMiddleware`. We replace only
        `input` for the current model step and then apply kwargs bound by
        `create_agent`, mainly `tools` and `tool_choice`.
        """
        if stop:
            raise NotImplementedError("`ChatNeMoGym` does not support `stop` sequences yet.")

        body = kwargs.pop("nemo_gym_body", None)
        if body is None:
            raise RuntimeError("`ChatNeMoGym` expected `NeMoGymMiddleware` to pass `nemo_gym_body`.")
        body = NeMoGymResponseCreateParamsNonStreaming.model_validate(body).model_dump(exclude_unset=True)
        body["input"] = _messages_to_items(messages)

        for key in ("max_output_tokens", "temperature", "top_p", "top_logprobs", "parallel_tool_calls"):
            if kwargs.get(key) is not None:
                body[key] = kwargs[key]
        if kwargs.get("max_tokens") is not None and kwargs.get("max_output_tokens") is None:
            body["max_output_tokens"] = kwargs["max_tokens"]

        tools = kwargs.get("tools")
        if not tools:
            raise RuntimeError("`ChatNeMoGym` expected `create_agent` to bind non-empty Decomposer `tools`.")
        body["tools"] = [_to_responses_tool(tool) for tool in tools]

        tool_choice = kwargs.get("tool_choice")
        body["tool_choice"] = _to_responses_tool_choice(tool_choice) if tool_choice is not None else "auto"

        body = NeMoGymResponseCreateParamsNonStreaming.model_validate(body)

        model_response = await self.server_client.post(
            server_name=self.model_server_name,
            url_path="/v1/responses",
            json=body,
            cookies=_latest_cookies(messages),
        )
        await raise_for_status(model_response)
        response_json = await get_response_json(model_response)
        response = NeMoGymResponse.model_validate(response_json)

        message = _response_to_ai_message(response)
        return ChatResult(
            generations=[ChatGeneration(message=message)],
            llm_output={
                # LangChain copies `llm_output` into `AIMessage.response_metadata` for
                # the single-generation case. `DecomposerAgent.responses()` can then
                # recover Gym-native outputs without custom graph middleware.
                "nemo_gym_response": response_json,
                # Keep Gym/aiohttp cookies as-is, matching official Gym examples.
                # The next model call scans prior AI messages and passes them back.
                "nemo_gym_cookies": model_response.cookies,
            },
        )

    def bind_tools(
        self,
        tools: Sequence[dict[str, Any] | type | Callable[..., Any] | BaseTool],
        *,
        tool_choice: str | None = None,
        **kwargs: Any,
    ):
        """Bind Decomposer tools in the format expected by Gym Responses API.

        `create_agent` calls this before every model invocation when `tools` are
        available. `self.bind(...)` stores these kwargs until `BaseChatModel.ainvoke()`
        eventually forwards them to `_agenerate()`.
        """
        bound_kwargs = {"tools": [_to_responses_tool(tool) for tool in tools]}
        if tool_choice is not None:
            bound_kwargs["tool_choice"] = _to_responses_tool_choice(tool_choice)
        bound_kwargs.update(kwargs)
        return self.bind(**bound_kwargs)


@dataclass(frozen=True)
class NeMoGymContext:
    body: NeMoGymResponseCreateParamsNonStreaming


class NeMoGymMiddleware(AgentMiddleware):
    def wrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], ModelResponse],
    ) -> ModelResponse:
        return handler(_request_with_body(request))

    async def awrap_model_call(
        self,
        request: ModelRequest,
        handler: Callable[[ModelRequest], Awaitable[ModelResponse]],
    ) -> ModelResponse:
        return await handler(_request_with_body(request))


class DecomposerAgentConfig(BaseResponsesAPIAgentConfig):
    resources_server: ResourcesServerRef
    model_server: ModelServerRef
    subagent_types: Sequence[SubagentType]


class DecomposerAgentRunRequest(BaseRunRequest):
    model_config = ConfigDict(extra="allow")


class DecomposerAgentVerifyRequest(BaseVerifyRequest):
    model_config = ConfigDict(extra="allow")


class DecomposerAgentVerifyResponse(BaseVerifyResponse):
    model_config = ConfigDict(extra="allow")


class DecomposerAgent(SimpleResponsesAPIAgent):
    """Gym agent server for the first Decomposer version.

    Assumes LangGraph SDK subagent assistants are already running. For now,
    subagents do not receive Gym resource-server tool/session context.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)
    config: DecomposerAgentConfig

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.graph = create_decomposer_agent(
            decomposer_model=ChatNeMoGym(
                server_client=self.server_client,
                model_server_name=self.config.model_server.name,
            ),
            subagent_types=self.config.subagent_types,
            middleware=[NeMoGymMiddleware()],
            context_schema=NeMoGymContext,
        )

    async def responses(
        self,
        request: Request,
        response: Response,
        body: NeMoGymResponseCreateParamsNonStreaming = Body(),
    ) -> NeMoGymResponse:
        body = body.model_copy(deep=True)

        input_messages = _input_to_messages(body.input)
        initial_state = {"messages": input_messages}
        final_state = await self.graph.ainvoke(
            initial_state,
            context=NeMoGymContext(body=body),
        )
        all_messages = final_state["messages"]
        output_messages = all_messages[len(input_messages) :]
        output_items = _messages_to_items(output_messages)
        usage = _messages_to_usage(output_messages)

        model_response = None
        for message in reversed(output_messages):
            if isinstance(message, AIMessage) and "nemo_gym_response" in message.response_metadata:
                model_response = message.response_metadata["nemo_gym_response"]
                break
        if model_response is None:
            raise RuntimeError("Decomposer graph did not produce a `ChatNeMoGym` model response.")

        for k, v in request.cookies.items():
            response.set_cookie(k, v)
        model_server_cookies = _latest_cookies(output_messages)
        if model_server_cookies is not None:
            for k, v in model_server_cookies.items():
                response.set_cookie(k, v)

        return NeMoGymResponse.model_validate(model_response | {"output": output_items, "usage": usage})

    async def run(
        self,
        request: Request,
        body: DecomposerAgentRunRequest = Body(),
    ) -> DecomposerAgentVerifyResponse:
        cookies = request.cookies

        seed_session_response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/seed_session",
            json=body.model_dump(),
            cookies=cookies,
        )
        await raise_for_status(seed_session_response)
        cookies = seed_session_response.cookies

        response = await self.server_client.post(
            server_name=self.config.name,
            url_path="/v1/responses",
            json=body.responses_create_params,
            cookies=cookies,
        )
        await raise_for_status(response)
        cookies = response.cookies

        verify_request = DecomposerAgentVerifyRequest.model_validate(
            body.model_dump() | {"response": await get_response_json(response)}
        )

        verify_response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/verify",
            json=verify_request.model_dump(),
            cookies=cookies,
        )
        await raise_for_status(verify_response)
        return DecomposerAgentVerifyResponse.model_validate(await get_response_json(verify_response))

    async def aggregate_metrics(self, body: AggregateMetricsRequest = Body()) -> AggregateMetrics:
        response = await self.server_client.post(
            server_name=self.config.resources_server.name,
            url_path="/aggregate_metrics",
            json=body.model_dump(),
        )
        await raise_for_status(response)
        return AggregateMetrics.model_validate(await get_response_json(response))


def _input_to_messages(input: str | NeMoGymResponseInput) -> list[BaseMessage]:
    """Convert Gym Responses API `input` into LangChain `messages`."""
    if isinstance(input, str):
        return [HumanMessage(content=input)]

    messages = []
    for item in input:
        item_type = _item_get(item, "type")
        if item_type == "message":
            role = _item_get(item, "role")
            content = _input_content_to_text(_item_get(item, "content", ""))

            if role == "user":
                message = HumanMessage(content=content)
            elif role in {"system", "developer"}:
                message = SystemMessage(content=content)
            elif role == "assistant":
                message = AIMessage(content=content)
            else:
                raise NotImplementedError(f"Unsupported Gym message `role`: {role!r}")

        elif item_type == "function_call":
            arguments = _item_get(item, "arguments", "")
            call_id = _item_get(item, "call_id")
            name = _item_get(item, "name")
            try:
                args = json.loads(arguments)
            except json.JSONDecodeError as e:
                message = AIMessage(
                    content="",
                    invalid_tool_calls=[
                        {
                            "type": "invalid_tool_call",
                            "id": call_id,
                            "name": name,
                            "args": arguments,
                            "error": f"Invalid JSON arguments: {e}",
                        }
                    ],
                )
            else:
                if not isinstance(args, dict):
                    message = AIMessage(
                        content="",
                        invalid_tool_calls=[
                            {
                                "type": "invalid_tool_call",
                                "id": call_id,
                                "name": name,
                                "args": arguments,
                                "error": "Tool-call arguments must be a JSON object.",
                            }
                        ],
                    )
                else:
                    message = AIMessage(
                        content="",
                        tool_calls=[{"name": name, "args": args, "id": call_id}],
                    )
        elif item_type == "function_call_output":
            message = ToolMessage(
                content=_input_content_to_text(_item_get(item, "output", "")),
                tool_call_id=_item_get(item, "call_id"),
            )
        else:
            if item_type in _MULTIMODAL_CONTENT_TYPES:
                raise NotImplementedError(
                    "`DecomposerAgent` supports text-only input; "
                    f"multimodal input item type {item_type!r} is not supported."
                )
            raise NotImplementedError(f"Unsupported Gym input item `type`: {item_type!r}")

        messages.append(message)

    return messages


def _request_with_body(request: ModelRequest) -> ModelRequest:
    body = _item_get(request.runtime.context, "body")
    if body is None:
        raise RuntimeError("`NeMoGymMiddleware` expected runtime `context.body`.")

    model_settings = dict(request.model_settings)
    model_settings["nemo_gym_body"] = NeMoGymResponseCreateParamsNonStreaming.model_validate(body)
    return request.override(model_settings=model_settings)


def _messages_to_items(messages: list[BaseMessage]) -> list[NeMoGymResponseInputItem | NeMoGymResponseOutputItem]:
    """Convert LangChain `messages` into Gym Responses API input/output items."""
    items = []
    for message in messages:
        if isinstance(message, HumanMessage):
            items.append(
                NeMoGymEasyInputMessage(role="user", content=_message_content_to_text(message.content)).model_dump()
            )
        elif isinstance(message, SystemMessage):
            items.append(
                NeMoGymEasyInputMessage(role="system", content=_message_content_to_text(message.content)).model_dump()
            )
        elif isinstance(message, ToolMessage):
            items.append(
                NeMoGymFunctionCallOutput(
                    call_id=message.tool_call_id,
                    output=_message_content_to_text(message.content),
                    status="completed",
                ).model_dump(exclude_none=True)
            )
        elif isinstance(message, AIMessage):
            if "nemo_gym_response" in message.response_metadata:
                # Preferred path for runtime messages generated by `ChatNeMoGym`:
                # replay the exact Gym model-server output, including training fields.
                output_items = message.response_metadata["nemo_gym_response"]["output"]
            else:
                # Fallback for hand-authored LangChain assistant messages, especially
                # future few-shot examples. These are prompt items only; they should not
                # be treated as generated rollout output by `DecomposerAgent.responses()`.
                output_items = []
                if message.content:
                    output_items.append(
                        NeMoGymEasyInputMessage(
                            role="assistant",
                            content=_message_content_to_text(message.content),
                        ).model_dump()
                    )
                for tool_call in message.tool_calls:
                    output_items.append(
                        NeMoGymResponseFunctionToolCall(
                            name=tool_call["name"],
                            arguments=json.dumps(tool_call["args"]),
                            call_id=tool_call["id"],
                            status="completed",
                        ).model_dump(exclude_none=True)
                    )
            items.extend(output_items)
        else:
            raise NotImplementedError(f"Unsupported LangChain message `type`: {type(message).__name__}")

    return items


def _messages_to_usage(messages: list[BaseMessage]) -> NeMoGymResponseUsage | None:
    usage = None
    for message in messages:
        if not isinstance(message, AIMessage):
            continue

        response = message.response_metadata.get("nemo_gym_response")
        if isinstance(response, NeMoGymResponse):
            response_usage = response.usage
        elif isinstance(response, dict) and response.get("usage") is not None:
            response_usage = NeMoGymResponseUsage.model_validate(response["usage"])
        else:
            response_usage = None

        if response_usage is None:
            continue

        if usage is None:
            usage = response_usage
        else:
            usage.input_tokens += response_usage.input_tokens
            usage.output_tokens += response_usage.output_tokens
            usage.total_tokens += response_usage.total_tokens

            # Match Gym examples: keep aggregate nested details conservative.
            usage.input_tokens_details.cached_tokens = 0
            usage.output_tokens_details.reasoning_tokens = 0

    return usage


def _response_to_ai_message(response: NeMoGymResponse) -> AIMessage:
    """Project one Gym response into the `AIMessage` shape `create_agent` expects."""
    texts: list[str] = []
    tool_calls: list[dict[str, Any]] = []
    invalid_tool_calls: list[dict[str, Any]] = []

    for item in response.output:
        if item.type == "message":
            for content in item.content:
                if content.type == "output_text":
                    texts.append(content.text)
                elif content.type == "refusal":
                    texts.append(content.refusal)
        elif item.type == "function_call":
            try:
                args = json.loads(item.arguments)
            except json.JSONDecodeError as e:
                # Invalid tool calls are represented with LangChain's standard
                # field. `create_agent` will not execute them; repair/retry policy
                # belongs in an optional middleware, not this model wrapper.
                invalid_tool_calls.append(
                    {
                        "type": "invalid_tool_call",
                        "id": item.call_id,
                        "name": item.name,
                        "args": item.arguments,
                        "error": f"Invalid JSON arguments: {e}",
                    }
                )
                continue

            if not isinstance(args, dict):
                # LangChain executable tool calls require dict args.
                invalid_tool_calls.append(
                    {
                        "type": "invalid_tool_call",
                        "id": item.call_id,
                        "name": item.name,
                        "args": item.arguments,
                        "error": "Tool-call arguments must be a JSON object.",
                    }
                )
                continue

            tool_calls.append({"name": item.name, "args": args, "id": item.call_id})

    usage_metadata = None
    if response.usage is not None:
        usage_metadata = {
            "input_tokens": response.usage.input_tokens,
            "output_tokens": response.usage.output_tokens,
            "total_tokens": response.usage.total_tokens,
        }

    return AIMessage(
        content="\n".join(text for text in texts if text),
        tool_calls=tool_calls,
        invalid_tool_calls=invalid_tool_calls,
        usage_metadata=usage_metadata,
    )


def _latest_cookies(messages: list[BaseMessage]) -> Any | None:
    """Return the most recent model-server cookies stored on an AI message."""
    for message in reversed(messages):
        if not isinstance(message, AIMessage):
            continue
        if "nemo_gym_cookies" in message.response_metadata:
            return message.response_metadata["nemo_gym_cookies"]
    return None


def _to_responses_tool(tool: dict[str, Any] | type | Callable[..., Any] | BaseTool) -> dict[str, Any]:
    openai_tool = tool if isinstance(tool, dict) else convert_to_openai_tool(tool)

    if openai_tool.get("type") == "function" and "function" in openai_tool:
        responses_tool = {"type": "function", **openai_tool["function"]}
    elif openai_tool.get("type") == "function":
        responses_tool = dict(openai_tool)
    else:
        return openai_tool

    responses_tool.setdefault("strict", False)
    return responses_tool


def _to_responses_tool_choice(tool_choice: Any) -> Any:
    if isinstance(tool_choice, str):
        return tool_choice
    if isinstance(tool_choice, dict) and tool_choice.get("type") == "function" and "function" in tool_choice:
        return {"type": "function", "name": tool_choice["function"]["name"]}
    return tool_choice


def _message_content_to_text(content: Any) -> str:
    return _content_to_text(content, source="LangChain")


def _input_content_to_text(content: Any) -> str:
    return _content_to_text(content, source="Gym")


_TEXT_CONTENT_TYPES = frozenset({"text", "input_text", "output_text"})
_MULTIMODAL_CONTENT_TYPES = frozenset(
    {
        "audio",
        "computer_call_output",
        "file",
        "image",
        "image_generation_call",
        "image_url",
        "input_audio",
        "input_file",
        "input_image",
        "video",
    }
)


def _content_to_text(content: Any, *, source: str) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        raise NotImplementedError(
            f"`DecomposerAgent` supports only string or text-part {source} message content; "
            f"received {type(content).__name__}."
        )

    texts = []
    for part in content:
        if isinstance(part, str):
            texts.append(part)
            continue

        part_type = _item_get(part, "type")
        if part_type in _MULTIMODAL_CONTENT_TYPES:
            raise NotImplementedError(
                f"`DecomposerAgent` supports text-only input; multimodal {source} "
                f"content part type {part_type!r} is not supported."
            )
        if part_type in _TEXT_CONTENT_TYPES:
            text = _item_get(part, "text")
        elif part_type == "refusal":
            text = _item_get(part, "refusal")
        else:
            raise NotImplementedError(f"Unsupported {source} message content part `type`: {part_type!r}")

        if not isinstance(text, str):
            raise ValueError(f"{source} message content part {part_type!r} must contain string text.")
        texts.append(text)

    return "\n".join(texts)


def _item_get(item: Any, key: str, default: Any = None) -> Any:
    if isinstance(item, dict):
        return item.get(key, default)
    return getattr(item, key, default)


if __name__ == "__main__":
    DecomposerAgent.run_webserver()
